"XOR tree flattening" "xor_tree.v\nbuild top\nopt\nopt -time\nopt\nreport_timing" "SUCCEED" "Delay: 8"

# xor_tree - do not do global xor decomposition...
# xor_cmp - create logic with less invertions where possible...
